// Generated by CoffeeScript 1.6.3
(function() {
  var ObjectID, addUser, app, deleteUser, e, evtTemp, express, findUserById, getEvent, getEventByID, getLogin, getOnlineUser, getUserList, initLogin, io, isOnline, logOnline, m, path, port;

  path = require("path");

  express = require("express");

  app = express();

  m = require("mongoskin").db("localhost/new", {
    safe: false
  }).collection("guys");

  e = require("mongoskin").db("localhost/new", {
    safe: false
  }).collection("events");

  io = require("socket.io").listen(8888);

  ObjectID = require("mongodb").ObjectID;

  app.use(express.bodyParser());

  app.use("/app", express.compress());

  app.use("/app", express["static"](path.resolve(__dirname, "../app")));

  app.use("/app", function(req, res, next) {
    return res.send(404);
  });

  app.all("/", function(req, res) {
    return res.sendfile("index.html", {
      root: "../app"
    });
  });

  port = process.env.PORT || 80;

  app.listen(port);

  console.log("############DEV HOST ON PORT" + port + "#################");

  logOnline = function() {
    console.log("########isOnline is now:##########################");
    console.log(isOnline);
    return console.log("#################################################");
  };

  /*TESTDB*/


  evtTemp = {
    events: [
      {
        title: "小當家．友伴支援計劃 2013 義工訓練工作坊",
        start: new Date("2013/6/11 7:30"),
        end: new Date("2013/6/11 9:30"),
        url: "http://pella.sytes.net/#/events/info/51e3527a7105331be410b4f7",
        location: "九龍深水埗",
        backgroundColor: "blue"
      }, {
        title: "小當家．友伴支援計劃 2013 義工訓練工作坊",
        start: new Date("2013/6/18 7:30"),
        end: new Date("2013/6/18 9:30"),
        url: "http://pella.sytes.net/#/events/info/51e3527a7105331be410b4f7",
        location: "九龍深水埗",
        backgroundColor: "blue"
      }, {
        title: "小當家．友伴支援計劃 2013 義工訓練工作坊",
        start: new Date("2013/6/25 7:30"),
        end: new Date("2013/6/25 9:30"),
        url: "http://pella.sytes.net/#/events/info/51e3527a7105331be410b4f7",
        location: "九龍深水埗",
        backgroundColor: "blue"
      }, {
        title: "小當家．友伴支援計劃 2013 義工訓練工作坊",
        start: new Date("2013/7/2 7:30"),
        end: new Date("2013/7/2 9:30"),
        url: "http://pella.sytes.net/#/events/info/51e3527a7105331be410b4f7",
        location: "九龍深水埗",
        backgroundColor: "blue"
      }, {
        title: "小當家．友伴支援計劃 2013 [必須]",
        start: new Date("2013/7/20 10:00"),
        end: new Date("2013/7/20 12:30"),
        url: "http://pella.sytes.net/#/events/info/51e3527a7105331be410b4f7",
        location: "待定",
        backgroundColor: "green"
      }, {
        title: "小當家．友伴支援計劃 2013 [必須]",
        start: new Date("2013/7/30 10:00"),
        end: new Date("2013/8/3 12:30"),
        url: "http://pella.sytes.net/#/events/info/51e3527a7105331be410b4f7",
        location: "待定",
        backgroundColor: "green"
      }, {
        title: "小當家．友伴支援計劃 2013 [必須]",
        start: new Date("2013/8/10 10:00"),
        end: new Date("2013/8/10 12:30"),
        url: "http://pella.sytes.net/#/events/info/51e3527a7105331be410b4f7",
        location: "待定",
        backgroundColor: "green"
      }, {
        title: "小當家．友伴支援計劃 2013 [必須]",
        start: new Date("2013/8/13 10:00"),
        end: new Date("2013/8/13 12:30"),
        url: "http://pella.sytes.net/#/events/info/51e3527a7105331be410b4f7",
        location: "待定",
        backgroundColor: "green"
      }, {
        title: "小當家．友伴支援計劃 2013[可自由選擇出席]",
        start: new Date("2013/7/13 10:00"),
        end: new Date("2013/7/13 12:30"),
        url: "http://pella.sytes.net/#/events/info/51e3527a7105331be410b4f7",
        location: "待定",
        backgroundColor: "powderblue"
      }, {
        title: "小當家．友伴支援計劃 2013[可自由選擇出席]",
        start: new Date("2013/7/16 10:00"),
        end: new Date("2013/7/16 12:30"),
        url: "http://pella.sytes.net/#/events/info/51e3527a7105331be410b4f7",
        location: "待定",
        backgroundColor: "powderblue"
      }, {
        title: "小當家．友伴支援計劃 2013[可自由選擇出席]",
        start: new Date("2013/7/23 10:00"),
        end: new Date("2013/7/23 12:30"),
        url: "http://pella.sytes.net/#/events/info/51e3527a7105331be410b4f7",
        location: "待定",
        backgroundColor: "powderblue"
      }, {
        title: "小當家．友伴支援計劃 2013[可自由選擇出席]",
        start: new Date("2013/7/27 10:00"),
        end: new Date("2013/7/27 12:30"),
        url: "http://pella.sytes.net/#/events/info/51e3527a7105331be410b4f7",
        location: "待定",
        backgroundColor: "powderblue"
      }, {
        title: "小當家．友伴支援計劃 2013[可自由選擇出席]",
        start: new Date("2013/8/3 10:00"),
        end: new Date("2013/8/3 12:30"),
        url: "http://pella.sytes.net/#/events/info/51e3527a7105331be410b4f7",
        location: "待定",
        backgroundColor: "powderblue"
      }
    ]
  };

  e.update({}, {
    $set: {
      eventTemplate: evtTemp
    }
  });

  console.log(new Date("2013/8/3 310:00"));

  /*TESTDB*/


  getUserList = function(s, m) {
    return m.find({}, {
      name: 1,
      profilePic: 1,
      _id: 1
    }).toArray(function(error, result) {
      return s.emit("s2c", result);
    });
  };

  findUserById = function(s, m, id) {
    return m.findOne({
      _id: new ObjectID(id)
    }, {}, function(err, result) {
      return s.emit("s2c", result);
    });
  };

  isOnline = [];

  getLogin = function(s, m, msg) {
    s.join(msg.newID).leave(msg.originalID);
    isOnline[msg.newID.toString()] = true;
    delete isOnline[msg.originalID];
    return logOnline();
  };

  initLogin = function(s, m, newID) {
    s.join(newID);
    isOnline[newID] = true;
    return logOnline();
  };

  addUser = function(s, m, user) {
    var d;
    console.log(user);
    d = new Date();
    user.registered = d.toString();
    user._id = ObjectID();
    m.insert(user);
    return s.emit("userAddSuccess", {
      _id: user._id,
      name: user.name,
      profilePic: user.profilePic,
      success: true
    });
  };

  deleteUser = function(s, m, id) {
    return m.findOne({
      _id: ObjectID(id)
    }, {
      name: true,
      profilePic: true
    }, function(err, result) {
      m.remove({
        "_id": ObjectID(id)
      });
      console.log(result);
      return s.emit("deletedUser", result);
    });
  };

  getOnlineUser = function(s, m, msg) {
    return s.emit("onlineUser", isOnline);
  };

  getEvent = function(s, e, msg) {
    return e.find({}).toArray(function(err, result) {
      return s.emit("giveEvent", result);
    });
  };

  getEventByID = function(s, e, msg) {
    return e.findOne({
      _id: ObjectID(msg.event_id)
    }, {}, function(err, result) {
      return s.emit("giveEventByID", result);
    });
  };

  io.set("log level", 0);

  io.on("connection", function(s) {
    s.on("c2s", function(data) {
      var action;
      console.log(data);
      action = data.action;
      switch (action) {
        case "getUserList":
          return getUserList(s, m);
        case "findUserById":
          return findUserById(s, m, data.msg._id);
        case "getLogin":
          return getLogin(s, m, data.msg);
        case "initLogin":
          return initLogin(s, m, data.msg.newID);
        case "addUser":
          return addUser(s, m, data.msg.newUser);
        case "deleteUser":
          return deleteUser(s, m, data.msg._id);
        case "getOnlineUser":
          return getOnlineUser(s, m, data.msg);
        case "getEvent":
          return getEvent(s, e, data.msg);
        case "getEventByID":
          return getEventByID(s, e, data.msg);
      }
    });
    return s.on("disconnect", function() {
      return console.log("someone disconnected");
    });
  });

  console.log(new Date(2012, 10, 10, 10, 10, 10));

}).call(this);

/*
//@ sourceMappingURL=server.map
*/
