// Generated by CoffeeScript 1.6.3
(function() {
  console.log("start");

  angular.module("compile", [], function($compileProvider) {
    return $compileProvider.directive("compile", function($compile) {
      return function(scope, element, attrs) {
        return scope.$watch(function(scope) {
          return scope.$eval(attrs.compile);
        });
      };
    });
  });

}).call(this);

/*
//@ sourceMappingURL=testQRcode.map
*/
