// Generated by CoffeeScript 1.6.3
(function() {
  "use strict";
  var dt;

  dt = {};

  dt.slideup = function() {
    var drtObj, linkFunction;
    linkFunction = function(scope, elem, attrs) {
      return elem.on("click", function() {
        return $(this).slideUp();
      });
    };
    drtObj = {
      restrict: "A",
      scope: {},
      transclue: false,
      replace: true,
      link: linkFunction
    };
    return drtObj;
  };

  dt.qr = function() {
    var drtObj;
    return drtObj = {
      link: function(scope, element, attr) {
        var etext;
        console.log(attr.text);
        etext = scope.$eval(attr.text);
        if (etext) {
          return $(".qr").qrcode({
            width: 220,
            height: 220,
            text: etext
          });
        } else {
          $(".qr").qrcode({
            width: 220,
            height: 220,
            text: attr.text
          });
          return console.log($("canvas"));
        }
      },
      template: "<div style='position: relative' class='qr'><span id='p' style='z-index: 99999;color:pink;left:100px;top:100px;position: absolute;font-size:50px;background-color: palevioletred'>P</span></div>",
      restrict: "E"
    };
  };

  dt.gmap = function() {
    return {
      link: function(scope, element, attr) {
        var h, lat, lng, mlat, mlng, w;
        lat = scope.$eval(attr.lat);
        mlat = scope.$eval(attr.mlat);
        lng = scope.$eval(attr.lng);
        mlng = scope.$eval(attr.mlng);
        w = scope.$eval(attr.w) || 220;
        h = scope.$eval(attr.h) || 220;
        $(".gmap").gmap3({
          map: {
            options: {
              center: [lat, lng],
              zoom: 1,
              mapTypeId: google.maps.MapTypeId.STAELLITE
            }
          },
          marker: {
            values: [
              {
                latLng: [lat, lng]
              }, {
                latLng: [mlat, mlng]
              }
            ]
          }
        });
        $(".gmap").css("height", h);
        return $(".gmap").css("width", w);
      },
      template: "<div class='gmap'></div>",
      restrict: "E"
    };
  };

  dt.fullcal = function() {
    return {
      link: function(scope, elem, attrs) {
        var evt, nullevt;
        nullevt = {
          events: [
            {
              title: "You have no event Right now pal!",
              start: new Date(2013, 6, 17, 6, 30, 0),
              end: new Date(2013, 6, 17, 12, 0, 0)
            }
          ]
        };
        evt = scope.$eval(attrs.event) || nullevt;
        return $(document).ready(function() {
          return $("#fullCal").fullCalendar({
            header: {
              left: 'prev,next today',
              center: 'title',
              right: 'month,agendaWeek,agendaDay'
            },
            defaultView: "agendaWeek",
            events: evt,
            allDayDefault: false
          });
        });
      },
      template: "<div id='fullCal'></div>",
      restrict: "E"
    };
  };

  angular.module("myApp.directives", []).directive(dt);

}).call(this);

/*
//@ sourceMappingURL=directives.map
*/
