// Generated by CoffeeScript 1.6.3
(function() {
  exports.setup = function(app, mongoose) {
    var User;
    User = mongoose.model("User", {
      name: String,
      story: String
    });
    app.get("/users", function(req, res) {
      return User.find({}, function(err, docs) {
        return res.send(docs);
      });
    });
    app.get("/users/:id", function(req, res) {
      return User.findOne({
        _id: req.params.id
      }, function(err, data) {
        return res.send(data);
      });
    });
    app.post("/users/:id", function(req, res) {
      delete req.body._id;
      return User.update({
        _id: req.params.id
      }, req.body, function(err, affected) {
        return res.send(err);
      });
    });
    app.post("/users", function(req, res) {
      return User.create(req.body, function(err, user) {
        return res.send(user);
      });
    });
    return app.del("/users/:id", function(req, res) {
      return User.remove({
        _id: req.params.id
      }, function(err) {
        return res.send(err);
      });
    });
  };

}).call(this);

/*
//@ sourceMappingURL=users.map
*/
